name: batchmate
description: Pharmaceutical batch scanning and management app with comprehensive logging
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # QR Code Scanning
  qr_code_scanner: ^1.0.1
  mobile_scanner: ^3.5.6
  
  # Camera & OCR
  camera: ^0.10.5+9
  google_mlkit_text_recognition: ^0.9.0
  
  # UI & State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  
  # Local Storage & Preferences
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Permissions & Device Info
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  connectivity_plus: ^5.0.2
  
  # UI Components
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.4
  shimmer: ^3.0.0
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  
  # Logging & File Operations
  logger: ^2.0.2+1
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
